### ISSUE TITLE
Dopracowanie wyposażenia

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#10]
Trzeba poprawić nazwy broni z powodu update RHS`a [zrobione]
Dodanie zapasów medycznych z ACE [w trakcie pracy]
Dodanie zatyczek do uszu dla graczy [zrobione]
Dostosowanie wyposażenia jednostek (opis poniżej) [w trakcie pracy]

Trzeba poprawić wyposażenie jednostek na misje. Przykładowo 2 granaty dymne to max dla zwykłego żołnierza. Dla dowódcy np. 2 białe i 2 jakiegoś koloru (blufor niebieski, opfor czerowny a indfor zielony) i  medyk który ma kilka białych (myślę, że max 6 powinien mieć). To się też tyczy zwykłych granatów i innych części wyposażenia.

**Comment by Przemro** [comment]
Zostały poprawione błędy/braki wyposażenia (tyczy się KM`a u bluforu) oraz dodane zapasy medyczne (ilość może zostać zmienione jeszcze). Nie ruszyłem jeszcze niczego z ilością granatów oraz przygotowaniem skrzynek.

**Comment by jok3r1321** [comment]
zmieniłem ilość medykamentów przypadających na poszczególną jednostkę... tj. 12 bandaży, 4 morfiny, 1 epinefryna (w celu pozbycia się skrzynek z zapasami medycznymi na misjach) oraz dostosowałem frakcje aaf pod ACE

**Comment by Przemro** [comment]
@jok3r1321 Sprawdź dokładnie czy wszystko działa - chyba usunąłeś plecak dla mechanika (lub jakiegoś jemu podobnego) i jeszcze wtedy przydałoby się podsumowanie ile jest czego dla danego wyposażenia, np.

Wyposażenie spadochroniarzy to:
X bandaży
X morfin
X granatów dymnych białych
...
coś tego typu, interesują mnie tylko te zmienione rzeczy magazynki itp. nie muszą tutaj być.
(pamiętajcie że _bagsmall to spadochron)

**Comment by Przemro** [comment]
Poprawa plecaków dla jednostek - radia dla dowódcy (po respawn) itp.

**Comment by jok3r1321** [comment]
Stworzyłem osobne plecaki dla:
    dowódcy (po respawnie otrzyma długie radio)
    Medyka
    Strzelca KM
    Mechanika
    Strzelca AT

**Comment by Przemro** [comment]
Czy wszystko jest już zrobione? Czy jest coś jeszcze co można poprawić/ulepszyć w wyposażeniu?
