### ISSUE TITLE
Usprawnienie AI

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#100]
Przydałoby się poprawić trochę szybkość reakcji AI na graczy. Dokładnie chodzi mi tu o czas jaki czasami boty potrzebują by zrozumieć że są pod ostrzałem i należy coś z tym zrobić a nie iść dalej spokojnie.

Można też pobawić się opcjami i stworzyć więcej szablonów do DAC`a tak aby był np. miastowy gdzie AI będą starały wbijać do domów, lub zwiększyć przygważdżanie itp...

**Comment by Przemro** [comment]
Usprawnienie SI zostało dodane wstępnie, poza tym wprowadziłem kilka zmian dotyczących ostawień DAC`a. Trzeba zebrać się jednego dnia i przestudiować instrukcje DAC`a razem i poprawić opcje itp.

**Comment by Xawery94** [comment]
Dodane do wersji 1.3
