### ISSUE TITLE
Safezone nie działa

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#102]
Ostatni update spowodował, że safezon (postawiony z "trigera") nie działa poprawnie. Jego działanie jest globalne i uniemożliwia rozgrywkę.

**Comment by Xawery94** [comment]
Problem zostanie naprawiony na najbliższych dniach. Skrypt został gruntowanie przerobiony i pojawi się niebawem.

**Comment by Xawery94** [comment]
Po godzinach testów odkryłem, iż to nie mój skrypt od "safe zone" powoduje te błędy lecz to "safe start" z F3 nie wyłącza się i jest na stałe włączony. Teraz pytanie ponieważ napisałem nowy skrypt odpowiadający z "safe zone", jest on o tyle lepszy, że jest przypisany do miejsca respawnu danej fakcji. Oczywiście nie jest jeszcze rozwinięty i na razie usuwa tylko pociski i granaty natomiast ten mój wcześniejszy skrypt dodatkowo wyłącza "demage" na postaci. I teraz rzuca się pytanie czy mam dalej ulepszać nowy skrypt czy będziemy dalej korzystać ze starego? Oczywiście na najbliższych misjach powinien być zakaz korzystania z tego czasu "safe start", który to właśnie jest przyczyną błędów i do puki nie zostanie rozwiązana zagadka dlaczego tak się dzieje zaleca się korzystanie z mojego "safe zone", który działa poprawnie.

**Comment by Przemro** [comment]
Nadal by się przydało by naprawić "safestart" jako, że jest on jedyna opcja na PvP.

**Comment by Xawery94** [comment]
Znalazłem prawdopodobny błąd w zapisie jednego z "case". Zostało to poprawione #105, wymaga jeszcze małych testów lecz z moich wynika, że problem naprawiony. Nie jest też konieczne dodawanie nowego skryptu związanego z "safe zone" można będzie ciągle korzystać ze starszej wersji która wciąż jest lepszą opcją.
