### ISSUE TITLE
Połączenie szablonu z misją wsparcia MM

### ISSUE THREAD

**Issue by MefiTheBest** [Przemro/Szablon-misji#107]
Proponuję połączyć szablon z misją wsparcia dla MM zrobioną przez Xawerego. Myślę, że usprawni to pracę MM, gdyż wszystkie elementy do przekopiowania będą dostępne w jednym miejscu.

**Comment by Xawery94** [comment]
Tutaj się nie zgodzę z Tobą, ponieważ chcemy aby szablon byl niezależny od modow i lepiej trzymać te rzeczy osobno, także osobno je rozwijac/poprawiać

**Comment by Przemro** [comment]
Zauważ, że szablon jest uniwersalny. Zmienimy mody ale szablon nadal będzie działał, jeżeli dodamy do szablonu elementy z modów, np. ACE w tym momencie pojawia się ryzyko (to już się zdarzyło kiedyś) że ACE usunie jakiś moduł lub część moda. Wtedy szablon nie będzie sprawny, wyskoczy Ci informacja, że misja zawiera dodatkowe mody i bez nich jej nie odpalisz. Naprawianie tego to sporo roboty.
