### ISSUE TITLE
Logistyka

### ISSUE THREAD

**Issue by Xawery94** [Przemro/Szablon-misji#108]
Rzeczy do zrobienia w ramach logistyki:

- dodać brakujące wyposażenie (aktualnie brak narzędzi do rozbrajania, detonatora)
- dokończenie wyposażenia pojazdów logistyki (dodanie plecaków, ładunków, min [opcjonalne])

**Comment by Przemro** [comment]
Czego brakuje nadal logistyce?

**Comment by Xawery94** [comment]
W najbliższym update zostaną dodane plecaki do wyposażenia pojazdu logistyki i na razie na tym przystaniemy. W wyposażeniu pojazdu są już ładunki, narzędzia więc nie trzeba ich dodawać.
