### ISSUE TITLE
Latarki dla M4A1

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#115]
Frakcje US dla klas "pomocniczych" (amunicyjny, medyk itp.) używają M4A1, ale jak się okazało ta broń nie ma szyn bocznych przez co nie da się montować latarek itp.

**Comment by Xawery94** [comment]
Bronie zostały zamienione na trochę inny model kompatybilny z latarkami, teraz wszyscy mają latarki oprócz KM-a.
