### ISSUE TITLE
Waga i wyposażenie

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#118]
To raczej coś na dłuższą akcje, ale przydałoby się sprawdzić wszystkie wersje wyposażenia (lekkie, średnie, ciężkie) w wszystkich wariantach (dzień, noc) dla każdej klasy tak aby dopasować ilość sprzętu.

Aktualnie zdarzają się sytuacje, że przy lekkim wyposażeniu np. MAT nie może biegać itp. Do ustalenia jest ile mniej więcej ammo powinni mieć na misji gracze przy danym wyposażeniu oraz dostosowanie plecaków, by unikać noszenia ogromnego plecaka w którym jest jeden magazynek.

**Comment by Xawery94** [comment]
Jako pierwszą propozycją jest ogólne zmniejszenie ilości magazynków dla żołnierzy np.:
- Lekkie 6 do 8 mag,
- Średnie 9 do 10 mag,
- Ciężkie 11 do 12 mag,

Tutaj także trzeba by zwrócić uwagę na ilość pocisków do granatnika, ponieważ uważam że jest ich trochę za dużo ale to jeszcze można przemyśleć.

Taka zmiana odciąży już wagę, a także przyczyni się do oszczędzania amunicji oraz lepszego wykorzystania logistyki, gdyż będą częściej potrzebne zrzuty amunicji.

**Comment by Przemro** [comment]
Aktualny postęp pracy: [https://docs.google.com/spreadsheets/d/1oEjBevBUEbmSzdr0sFHPKgxLVYi77YYQFr85bEBUYlQ/edit?usp=sharing](url)
aktualizacje są na bieżąco.

**Comment by Xawery94** [comment]
Zostały dodane nowe ilości magazynków do arkusza, następnie należałoby jak najszybciej wprowadzić poprawki jeszcze prze dodawaniem nowych frakcji aby nie było później więcej pracy z kopiowaniem i przerabianiem tysiąc razy tego samego, a żeby nowe frakcje były robione już na nowej podstawie.

**Comment by Xawery94** [comment]
W kierunku zmian zostały zrobione duże kroki. W najbliższym update szablonu 1.4 pojawią się wszystkie dostępne frakcje na nowym systemie magazynków.
