### ISSUE TITLE
Fast rope

### ISSUE THREAD

**Issue by Xawery94** [Przemro/Szablon-misji#119]
Składam propozycje dodania skryptowej wersji "Fast Rope", która może urozmaicić nasze rozgrywki. Jest to wersja skryptowa współpracująca z ACE 3, a także którą można dowolnie przerabiać/zmieniać do naszych potrzeb. Jestem w stanie przerobić skrypt, tak aby działał na naszych modach, a także podjąć się próby wdrożenia tego skryptu do naszego szablonu, aż DO CZASU, gdy ACE nie doda swojej wersji "Fast Rope", w tedy wystarczy tylko usunąć wersje skryptową i po kłopocie.

Podsyłam także filmik prezentujący skrypt: https://www.youtube.com/watch?v=hvUsmf3A0fg

Dodatkowym plusem jest to, że skoro jest to wersja skryptowa można dowolnie określać na jakich pojazdach ma być dostępny "Fast Rope".

**Comment by Przemro** [comment]
Zamykać, skoro nie działa dla JIP? Czy chcesz jeszcze z tym walczyć?

**Comment by Xawery94** [comment]
Raczej zamykam. Poczekamy na ACE 3. Jest to dosyć skomplikowany problem i nie ma zachodu nad nim siedzieć skoro za chwile ACE wyda swoją wersje.
