### ISSUE TITLE
Ulepszenie wyspożenia Medyka 

### ISSUE THREAD

**Issue by Topolek** [Przemro/Szablon-misji#120]
Propozycja moja i paru innych ludzi, a o co chodzi ?
Quick loty przestały być efektywne przez co nie raz schodzi po 7 bandaży aby komuś zabandażować kończynę a na to niestety nie ma czasu na polu walki. Propozycja polega na tym, aby medycy dostali 2 typy bandaży (Uciskowy i Elastyczny(najbardziej przydatne)) które znacznie przyspieszą prace medyka ale również urozmaicą ponieważ będzie musiał myśleć jaki bandaż musi użyć na dany typ rany. Oczywiście wiązało by się to z dodatkowymi szkoleniami dla medyków (których prowadzenia mogę się podjąć).

**Comment by Przemro** [comment]
Problem leży po stronie ACE, jak przeczytasz dokumentacje dostępną na ich stronie, dowiesz się że skuteczność opatrunku typu QuikClot jest uniwersalnie najwyższa.
http://ace3mod.com/wiki/feature/medical-system.html#bandages-effectiveness

**Comment by Xawery94** [comment]
Zamykam. Teraz wydaje się że wszystko działa poprawnie.
