### ISSUE TITLE
Logi markerów

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#124]
http://killzonekid.com/arma-scripting-tutorials-whos-placingdeleting-markers/

Dodanie w celu "pilnowania" porządku na misjach. Na ile wiem powyższy kod działa z jego jakąś konsolą, fajnie gdyby dało się to zrobić do pliku tekstowego np. "markery.log"

**Comment by Xawery94** [comment]
To jak już to ja proponuje dodać "Sweet markers system" https://forums.bistudio.com/topic/174023-sweet-markers-system. Dodaje on o wiele więcej możliwości przykładowo przesuwania postawionego markera, logi [kto postawił/usunął] oraz ciekawa funkcja zapisywania postawionych wcześniej markerów po stronie klienta co umożliwia później ich szybkie wczytanie na początku misji [znalazło by się kilka przykładów zastosowania np. dowódca wczytuje sobie radia, które wcześniej rozpisał u siebie na mapie lub wczytuje wstępny plan i tylko dorysowuje/zmienia zależnie od drużyn].

**Comment by Przemro** [comment]
Już zrobione i sprawdzone, zamykam. - Co do moda, i tak używamy kropek jako oznaczeń i chce by tak na razie zostało.
