### ISSUE TITLE
Headless nie działa!!

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#127]
To jest kwestia priorytetowa aktualnie, trzeba naprawić headlessa inaczej serwer ma duże problemy z misjami. Z standardowych fps 40 - 50 bez headlessa mamy nawet 1 fps.

**Comment by Xawery94** [comment]
Problem znany i spowodowany przez zmienioną mechanikę w Armie po ostatnim update 1.56 . Musimy czekać na patche ze strony BI lub twórcy moda Werthles' Headless Module 
[ https://forums.bistudio.com/topic/184485-werthles-headless-module ], aż uda mu się naprawić mechanikę HC.

Zamykam
