### ISSUE TITLE
Część skryptów nie działa

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#128]
Gracz, który wyjdzie z serwera po powrocie nie otrzymuje swojego wyposażenia, na slotach JIP nie działa akcja wsparcia itp.

**Comment by Xawery94** [comment]
Jest to bug spowodowany przez mechanikę w Eden i nic z tym nie zrobimy. Jedyne wyjście to pozostać na edytorze 2d, aż problem nie zostanie rozwiązany/naprawiony przez BI.

Zamykam - niemożliwe do naprawy
