### ISSUE TITLE
Broń US 80/90

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#133]
- [x] Podmienić bronie z CUP na RHS, lepsza jakość

- [x] Zabranie wszelkich celowników do broni podstawowych. 80/90

- [x] Upewnić się, że MAT z USA 2010 ma celownik to AT (SMAW)

- [x] W frakcjach USA 80/90 kamizelki nie maja działających kabur przez co bronie są  miedzy nogami graczy.

**Comment by Xawery94** [comment]
Zostało tylko podmienić bronie
