### ISSUE TITLE
II Wojna Światowa

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#138]
Jeżeli dodamy mod IF, trzeba będzie przygotować odpowiednie frakcja dla graczy. Kwestia jest, jak rozwiązać problemy sprzętowe, a raczej różnice w broniach. Przykładowo takie drużyny jak MMG, SAM(AA) stracą raczje bytu, podobnie może być z MATem.

**Comment by Xawery94** [comment]
Jeszcze nie wiem jak to dokładnie wygląda z rodzajami broni, ale pewnie coś się wymyśli.

**Comment by Przemro** [comment]
Wszystko dotyczące tego znajdzie się tutaj: https://github.com/Xawery94/Szblon-misji-IF

Zamykam.
