### ISSUE TITLE
Więcej frakcji

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#2]
Dodanie więcej frakcji dla graczy jak rosyjskie VDV czy amerykańskie USMC i innych w zależności od modów.

Dodanie również frakcji do DAC`a, by móc walczyć przeciwko wymienionym jednostką.

Planowane jednostki:
1. Rosyjskie VDV [dodano]
2. SLA (armia z Army 1) [dodano]
3. US Army (pustynne i leśne)
4. USMC (pustynne i leśne) [dodano]
5. ChDKZ [dodano]
6. Taliby [dodano]
7. Afrykańscy bojownicy
8. Europejscy bojownicy
9. Separatyści z Ukrainy (może)
10. PMC (jak zostaną dodani do paczki)

Może cywile w przyszłości.

**Comment by Doseq** [comment]
PMC /Lepiej uzbrojeni najemnicy .

**Comment by Przemro** [comment]
1. Rosyjskie VDV [dodano]
2. SLA (armia z Army 1) [dodano]


5. ChDKZ [dodano]
6. Taliby [dodano]

**Comment by Przemro** [comment]
USMC pustynne zostały dodane jako frakcja dla graczy.

**Comment by jok3r1321** [comment]
dodałem USMC WD oraz PMC jako frakcje dla gracza

**Comment by jok3r1321** [comment]
dodałem Afghan Police, Afghan Army (Desert), Afghan Army (Woodland) oraz Talibów jako frakcje dla gracza

**Comment by Xawery94** [comment]
Dodane: Afghan Police, Afghan Army dla DAC-a

**Comment by Przemro** [comment]
Do dodania frakcje CDF i Takistan dla graczy!

**Comment by jok3r1321** [comment]
dodałem CDF i TK

**Comment by Przemro** [comment]
Na chwile obecną wszystko co było na liście dodane, zamykam.
