### ISSUE TITLE
Dodanie trybu obserwatora do misji

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#26]
Generalnie chodzi o dodanie możliwości przełączenia się w tryb obserwatora w dowolnym momencie gry (skutkuje to śmiercią postaci w grze) - jest to z zamysłem dla ludzi którzy zginą i nie ma dla nich aktualnie nic do roboty (jak logistyka i wsparcie) by się nie nudzili i nie rozpierdalali bazy będą mogli się przełączyć na obserwatora i oglądać misje.

**Comment by Przemro** [comment]
Wrzuciłem skrypt dodający obserwatora ( http://www.armaholic.com/page.php?id=27948 ), teraz pozostaje dodać akcje, która aktywuje skrypt np. tabliczkę w bazie. Do aktywacji:
spawn CSSA3_fnc_createSpectateDialog

**Comment by Przemro** [comment]
Przy próbie włączenia wyskakuje błąd ( http://zapodaj.net/images/c6552a64b4d93.png )
@Xawery94 czy możesz wrzucić linka do misji? (spakowana w .rar - nie .pbo)

**Comment by Xawery94** [comment]
Tak jutro postaram się podesłać tą misję.

**Comment by Przemro** [comment]
@szelf dałbyś rade nas z tym podratować, bo to zaczyna robić się bardzo ważne teraz na misjach.

**Comment by Przemro** [comment]
Daj znać @szelf jak będziesz miał coś nowego do testów.

**Comment by Przemro** [comment]
@szelf 
https://github.com/Sniperhid/1Tac-F3/blob/master/f/respawn/fn_RespawnLocalClient.sqf
Może to się przyda do rozwiązania problemu ZEUSa i znikającej odprawy, goście z F3 mi to podrzucili.

**Comment by Xawery94** [comment]
Została dodana juz poprawiona wersja. Przacwalismy wspólnie z Szelfem i udalo nam się naprawic znikajacą odprawe. Pozostal problem znikajacego zeusa lecz admin w swojej odprawie dostaje Admin Menu przez które moze nadac zeusa na siebie. Wiec jest to problem niskiej wagi. Co do tego problemu z TFR zostal dodany log do RPT aby ułatwić szukanie błędu gdy takowy sie pojawi.

**Comment by Przemro** [comment]
Zamykam, jakieś błędy należy w nowym zgłoszeniu.
