### ISSUE TITLE
Czy szablon powinien być zależy od modów?

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#28]
Zauważyłem, że w szablonie pojawiły się moduły z ACE3. Zastanawiam się czy to dobry pomysł, utrzymanie szablonu niezażeganego od modów jest bardzo wygodne dla ludzi, bo mogą w każdym wypadku zrobić misje i nawet jak jakiś mod się popsuje szablon będzie działał. W aktualnie sytuacji jak byśmy usunęli ACE z modów robi się problem, bo szablonu nie da się włączyć bez ACE.

Myślę, że lepiej by szablon został niezależny a informacje o dodaniu ACE itp. powinny być w poradniku. Wyposażenie dla klas jest oskrypotwane, więc utrata moda jak RHS spowoduje tylko, że jednostki zrespią się "puste" ale nie wpłynie to na możliwość uruchomienia szablonu.

**Comment by jok3r1321** [comment]
ACE już usunięty z szablonu
