### ISSUE TITLE
Sloty JIP dostają radia

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#37]
Dodane zostały sloty JIP, ale z niewiadomych przyczyn gracze po skorzystaniu z opcji wybrania drużyny i wyposażenia zamiast odpowiedniego plecaka dostają radio długie.

**Comment by Przemro** [comment]
@szelf - dasz radę sprawdzić co tam się dzieję?

**Comment by szelf** [comment]
Nie dam rady, Przemro. 
Spędziłem wczoraj ponad 12 upojnych godzin pracy zawodowej
( zawsze tak jest przed urlopem :( ), a dziś wyjeżdżam na urlop.

**Comment by Przemro** [comment]
Dobra wstawiłem wersje, która powinna poprawić problem z slotami JIP. Przydałoby się zrobić test tego, czy to zadziała poprawnie.

**Comment by Przemro** [comment]
Naprawione - zamykam
