### ISSUE TITLE
BAF i lornetka

### ISSUE THREAD

**Issue by Xawery94** [Przemro/Szablon-misji#43]
BAF powoduje, że nie można wyciągnąć lornetki. Tak jakby usuwa ją i nie da się jej używać.

**Comment by jok3r1321** [comment]
zastąpie lornetki vectorem i nie będzie problemu. Chyba że usuwamy BAFa ^^

**Comment by Przemro** [comment]
To się tyczy tylko podstawowej armowej lornetki?
Jeżeli tak, to można dowódcą dać znaczniki laserowe a amunicyjnym rangefindery (vectory) albo jakoś tak.

**Comment by jok3r1321** [comment]
tyczy się to tylko lornetki "binocular" (czyli podstawowej armowej). Dowódcą zamienie ją na vectory a amunicyjni mają już od dawna rangefindery.
