### ISSUE TITLE
Przedmioty z ACE

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#45]
Trzeba dodać przedmioty z ACE jak zestaw do rozbrajania ładunków itp. do  odpowiednich jednostek. Też dla klas które zajmują się ładunkami, trzeba ustalić które i ile ładunków mieć powinni.

**Comment by jok3r1321** [comment]
dodałem zestaw do rozbrajania, zapalnik oraz zmieniłem ilość ładunków
