### ISSUE TITLE
Zaawansowany system medyczny ACE

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#48]
Trzeba dowiedzieć się jakich przedmiotów potrzebują medycy w zaawansowanym systemie medycznym, oraz co powinien mieć zwykły piechociarz. Zorbie też osobną gałąź dla ACE.

**Comment by szelf** [comment]
Umieszczam tu moją propozycję wyposażenia żołnierzy i medyków.
Uwagi : 
* Zestaw pierwszej pomocy ( ang. Personal Aid Kit ) może być używany przez żołnierzy tylko w przypadku gdy zostaną ustawione odpowiednie opcje w module ACE_medical. Ponadto - ważne jest, że ten zestaw jest stosunkowo ciężki ( 1 kg ) i znika po użyciu. 
* Zarówno propozycja moja, jak i ACE3 nie daje medykowi polowemu krwi i osocza, które powinny być przechowywane w lodówkach, aby być całkowicie skuteczne. Zamiast tego medyk jest wyposażony w sól fizjologiczną. W propozycji ACE 3 jest dodatkowe stanowisko paramedyka przemieszczającego się pojazdem i on posiada i krew i osocze ( znajdujące się na wyposażeniu pojazdu. ACE3 zakłada, że taki pojazd jest wyposażony w lodówkę do przechowywania płynów transfuzyjnych ).
* W propozycji ACE3 chyba przesadzili z ilością atropiny. Z naszych dotychczasowych testów wynika, że nie jest ona tak ważna jak np. epinefryna.
* To czy zestaw do szycia ran znika po uzyciu zależy od ustawień modułu ACE_medical. Jeśli ma nie znikać, to jego liczbę możemy zmniejszyc do jednej sztuki. Wtedy masa zestawu medyka spadnie o 3 kg.

**Proponowane wyposażenie żołnierza**

Nazwa ARMA 3| Nazwa polska | Masa (kg) | Propozycja ACE3 | Masa | Moja propozycja | Masa
----- | ------------ | --------- | --------------- | ---- | --------------- | ----
ACE_fieldDressing | bandaż jałowy | 0,1 | 4 | 0,4 | 0 | 0
ACE_packingBandage | bandaż uciskowy  | 0,1 | 3 | 0,3 | 2 | 0,2
ACE_elasticBandage | bandaż elastyczny | 0,1 | 3 | 0,3 | 8 | 0,8
ACE_quikclot | opatrunek Quik Clot | 0,1 | 3 | 0,3 | 4 | 0,4
ACE_tourniquet | opaska uciskowa | 0,1 | 1 | 0,1 | 1 | 0,1
ACE_morphine | morfina | 0,1 | 1 | 0,1 | 1 | 0,1
ACE_personalAidKit | zestaw pierwszej pomocy | 1 | 0 | 0 | 1 | 1

Masa całkowita zestawu żołnierza wg. ACE 3 = 1,5 kg
Masa całkowita propozycji zestawu żołnierza = 2,6 kg
 
**Proponowane wyposażenie medyka**
 
Nazwa ARMA 3| Nazwa polska | Masa (kg) | Propozycja ACE3 | Masa | Moja propozycja | Masa
----- | ------------ | --------- | --------------- | ---- | --------------- | ----
ACE_fieldDressing | bandaż jałowy | 0,1 | 15 | 1,5 | 0 | 0
ACE_packingBandage | bandaż uciskowy  | 0,1 | 8 | 0,8 | 10 | 1
ACE_elasticBandage | bandaż elastyczny | 0,1 | 20 | 2 | 30 | 3
ACE_quikclot | opatrunek Quik Clot | 0,1 | 15 | 1,5 | 20 | 2
ACE_tourniquet | opaska uciskowa | 0,1 | 5 | 0,5 | 5 | 0,5
ACE_morphine | morfina | 0,1 | 8 | 0,8 | 10 | 1
ACE_atropine | atropina | 0,1 | 12 | 1,2 | 6 | 0,6
ACE_epinephrine | epinefryna | 0,1 | 8 | 0,8 | 10 | 1
ACE_bloodIV | Krew 1000 ml | 1 | 0 | 0 | 0 | 0
ACE_bloodIV_500 | Krew 500 ml | 0,5 | 0 | 0 | 0 | 0
ACE_bloodIV_250 | Krew 250 ml | 0,25 | 0 | 0 | 0 | 0
ACE_plasmaIV | Osocze 1000 ml | 1 | 0 | 0 | 0 | 0
ACE_plasmaIV_500 | Osocze 500 ml | 0,5 | 0 | 0 | 0 | 0
ACE_plasmaIV_250 | Osocze 250 ml | 0,25 | 0 | 0 | 0 | 0
ACE_salineIV | Sól fizjologiczna 1000 ml | 1 | 0 | 0 | 2 | 2
ACE_salineIV_500 | Sól fizjologiczna 500 ml | 0,5 | 6 | 3 | 6 | 3
ACE_salineIV_250 | Sól fizjologiczna 250 ml | 0,25 | 0 | 0 | 0 | 0
ACE_personalAidKit | zestaw pierwszej pomocy | 1 | 3 | 3 | 3 | 3
ACE_surgicalKit | Zestaw do szycia ran | 1,5 | 3 | 4,5 | 2 | 3
ACE_bodyBag | Worek na zwłoki | 2 | 0 | 0 | 0 | 0

Masa całkowita zestawu medyka wg. ACE 3 = 19,6 kg
Masa całkowita propozycji zestawu medyka = 20,1 kg

**Comment by MASZARA** [comment]
Moja propozycja wyposażenia medyka i żołnierza 

Wyposażenie żołnierza:
bandaż uciskowy- 8
bandaż elastyczny-3
opatrunek Quik Clot-2
opaska uciskowa-1
zestaw pierwszej pomocy-1

Wyposażenie medyka:
bandaż uciskowy-30
bandaż elastyczny-15
opatrunek Quik Clot-15
opaska uciskowa-8
morfina-10
atropina-5
epinefryna-15
Sól fizjologiczna 1000 ml-2
Sól fizjologiczna 500 ml-5
Sól fizjologiczna 250 ml-2
Zestaw do szycia ran-3 (przyjmując że jest jednorazowy)
zestaw pierwszej pomocy-1 (jedynie do własnego opatrywania się gdyż medyk sam nie może zaszyć sobie ran)

**Comment by Przemro** [comment]
Jako że zwykła piechota nie będzie miała pełnego szkolenia dotyczącego systemu medycznego, wstępnie otrzymają tylko opatrunki Quik Clot(są dosyć uniwersalne ale pozostanie nada potrzeba sprawdzenia ran przez medyka), po wstępnych testach i reakcji ludzi rozważy się dodanie innych rodzajów bandazy. Każdy również otrzyma jeden zestaw pierwszej pomocy.

Zestaw do szycia ran będzie wielokrotnego użycia - jako że w wielu modach nie ma pojazdów medycznych, medycy muszą byc w stanie każdego uleczyc na 100% - mechanika pojazdów medycznych i namiotu zostanie sprawdzona podczas testów.

Co do działania krwi i alternatywy jak osocze itp. - myślę że zrobimy kilka testów z różnymi środkami, jako że liczebność klanu jest za mała by tworzyć dedykowana drużynę medyczną, zostaniemy głównie przy środkach pomocy na polu bitwy nie w bazie itp.

**Comment by Przemro** [comment]
Pierwsza wersja została dodana już, na bazie szablonu i waszych sugestii tak wyglądają wyposażenia.

Dodanie wyposażenia medycznego dla każdego gracza:
12 - opatrunek "Quik Clot"
1 - opaska uciskowa
2 - morfina
1 - zestaw pierwszej pomocy

Dodanie medykowi do plecaka wyposażenia medycznego:
18 - opatrunek "Quik Clot" (każdy dostaje 12 na start, medyk ma łącznie 30 opatrunków)
30 - bandaż uciskowy
30 - bandaż elastyczny
4 - opaska uciskowa (każdy dostaje jedna opaskę uciskową, medyk ma łącznie 5)
13 - morfina (każdy dostaje 2, medyk ma łącznie 15)
10 - atropina
15 - epinefryna
8 - sól fizjologiczna 500 ml
1 - zestaw do szycia ran (będzie on wielokrotnego użytku)
6 - zestaw pierwszej pomocy (by inni gracze mogli uzupełnić zapasy)

**Comment by Przemro** [comment]
W następnej wersji ogranicze bandaże do jednego rodzaju (opatrunek "Quik Clot") a pozostałe zostaną  usunięte łącznie z opaskami uciskowymi.

**Comment by Przemro** [comment]
Kolejna wersja jest gotowa, teraz potrzeba przeprowadzić testy, czy wszystko poprawnie będzie działać.

**Comment by Przemro** [comment]
Pierwszy moduł
![ace1](https://cloud.githubusercontent.com/assets/7649811/10017835/12ff57e4-6132-11e5-95f5-182f6b5a08bd.jpg)

Drugi moduł:
![ace2](https://cloud.githubusercontent.com/assets/7649811/10017854/27b5fc74-6132-11e5-9b6c-208ce0be6f33.jpg)
![ace3](https://cloud.githubusercontent.com/assets/7649811/10017857/2c5cb218-6132-11e5-9a86-1449a8fc7d35.jpg)

**Comment by Przemro** [comment]
Myślę, że tutaj zostało wszystko zrobione czsowo.
