### ISSUE TITLE
TAW View Distance Script

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#55]
Trzeba dodać TAW view distance script: http://www.armaholic.com/page.php?id=19751
W tym szablonie jest już dodana: https://github.com/Phantomsmedia/Wavelength/tree/master/WL.VR

**Comment by Przemro** [comment]
ACE dodaje własny system ustawienia odległości - brakuje w nim opcji wyłączenia trawy.

**Comment by Xawery94** [comment]
Zamykam
