### ISSUE TITLE
Więcej zachowań w DAC`u

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#56]
Fajnie by było, gdyby dodać więcej zachować dla botów. Mam tutaj na myśli blufor w trybie patrolowym tylko, blufor na full speed itp. dla reszty frakcji (chodzi też by ustawić moździerze - bo tam się to ustawia), można też dodać zachowanie dla cywilów (powoli i bezpiecznie) może nie będą się zabijać na misji jak "Wymiana".

**Comment by Xawery94** [comment]
Wstępnie zrobione. Zamykam.
