### ISSUE TITLE
Radia dla drużyn AA

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#59]
Osoby z drużyn AA (lub SAM) nie dostają radia krótkiego, trzeba sprawdzić pliki tfr w szablonie.

**Comment by Xawery94** [comment]
W HMG też brakuje radia.

**Comment by Przemro** [comment]
Trzeba sprawdzić inne drużyny jak moździerz, HAT itp. i nadać im radia.

**Comment by Xawery94** [comment]
Problem naprawiony.
