### ISSUE TITLE
Pilot samolotu

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#61]
Można dodać osobna klasę pilota samolotu, odpowiedni strój itp. + spadochron bo pilot śmigłowca nie zawsze pasuje do samolotu.

**Comment by Xawery94** [comment]
Zrobione, zostanie to dodane w najbliższym update.

**Comment by Xawery94** [comment]
Zrobione. Ewentualne błędy w kolejnych zgłoszeniach.
