### ISSUE TITLE
Stroboskopy

### ISSUE THREAD

**Issue by Xawery94** [Przemro/Szablon-misji#69]
Proponuje dodanie większej ilości stroboskopów, może tak z 5-10 szt., gdyż teraz po 20 min się wyczerpują i są one jednorazowego użytku. Warto to dodać, gdyż są one przydatne gdy prowadzimy nocne misje.

**Comment by Przemro** [comment]
W wyposażeniu dla gracza nie ma za bardzo miejsca na tyle stroboskopów, lepszym rozwiązaniem będzie dodanie ich do skrzynek z zaopatrzeniem.

**Comment by Xawery94** [comment]
Zrobione, zostanie to dodane w najbliższym update.
