### ISSUE TITLE
Dodanie wyposażenia do pojazdów

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#72]
Zastanawiam się nad przygotowaniem wyposażenia dla pojazdów, działać będzie to na tej samej zasadzie jak skrzynki z zaopatrzeniem. Kwestia jest co powinno być w pojeździe i jak rozwiązać problem różnych pojazdów (czołg/IFV/APC/samochód itp.).

Wstępnie w pojazdach widzę lekkie wyposażenie, np. max 5 magazynków do głównej broni frakcji jak M4 oraz jakaś mała ilość zapasów medycznych, ewentualne narzędzia. Nie chcę by pojazdy były jeżdżącymi skrzynkami z zaopatrzeniem, dlatego chce by miały rzeczy przydatne ale nie takie ilości zapasów by eliminować potrzebę zabierania skrzynki z bazy lub potrzebę logistyki.

Inna sprawa by pojazdy nie miały sprzętu który wykracza poza wyposażenie piechoty, np. by nie było 10 GPS`ów lub innych tego typu rzeczy.

Jakieś pomysły co można dodać do pojazdów, co faktycznie pasuje do ich wyposażenia?

**Comment by Xawery94** [comment]
Dodałem wstępną propozycje wyposażenia pojazdów:
___
1.Samochód:
* 2 magazynki,
*
*
*

**Comment by Przemro** [comment]
Karabiny będą zaraz zabrane przez np. zmech za ich MP5. Myślę że nie ma co dawać tego, można za to pomyśleć nad dodaniem jednej wyrzutni, takiej awaryjnej. (broń główna każdy ma, tubę juz nie)

**Comment by Xawery94** [comment]
Broń dla pojazdów pancernych została dodana na wszelki wypadek, gdy dojdzie do poważnego uszkodzenia pojazdu, wtedy można wykorzystać te dwa karabiny. ja zawsze pilnuje aby nie brać ich już na początku tylko w nadzwyczajnych wypadkach. 
A co do tej tuby to można też dodać np. jedną lub dwie.

**Comment by Przemro** [comment]
Jeżeli chodzi o tuby to jedna to max i nożyce też tylko raz, można też pomyśleć o wyposażeniu pojazdu logistyki.

**Comment by Xawery94** [comment]
Daję tutaj propozycje wyposażenia pojazdu wsparcia. (*Daję tutaj przykład zanim jeszcze zacznę cokolwiek robić w szablonie.*) Jest to przykład tylko dla jednego pojazdu, który by był na całą mapę. Nie chciałem dawać tutaj tego za dużo, aby nie było takiej sytuacji że nie będzie trzeba brać zapasów ze skrzyń zaopatrzenia z bazy. Według mnie ma być to pojazd który jest do szybkiego zaopatrzenia na linii frontu, a jeśli wymagane by były większe zapasy to trzeba by dostarczyć skrzynię z bazy.

____
- 4 karabin M4,
- 30 magazynki,
- 6 AT,
- 10 granaty,
- 10 granaty dymne (5/5 biały i niebieski),
- 20 bandaży,
- 10 morfiny,
- 5 epi,
- 15 IR Strobe
- 2 Toolkit,
- 6 Ładunki wybuchowe,
- 2 Zapalniki,
- 2 Nożyce do cięcia drutu.
____

Tak jak napisałem był by tylko jeden taki pojazd na mapę ewentualnie można podzielić te zapasy na dwa pojazdy tak w razie gdyby jeden uległ zniszczeniu.

**Comment by Przemro** [comment]
Ja się zajmę zrobieniem tego. Tylko nadal wydaje mi się, że jednak lepiej gdyby nie było M4 w pojazdach czy dowolnej broni dla frakcji.

**Comment by Xawery94** [comment]
Aktualnie zostało nadane wyposażenie opisane w tym poście we wszystkich frakcjach oprócz BAF i zostanie wprowadzone w najbliższym update.

**Comment by Xawery94** [comment]
Zrobione. Ewentualne błędy w kolejnych zgłoszeniach.
