### ISSUE TITLE
Raport z 30.10

### ISSUE THREAD

**Issue by Xawery94** [Przemro/Szablon-misji#74]
Raport z ostatniej aktywności:

1. Drobne poprawki w skrypcie Spektatora,
2. Dodanie przełączenia trybu ognia na "SAFE" po respawnie,
3. Dodanie ulepszonej notatki "Orbat",
4. Dodanie ulepszonej notatki "Loadout",
5. Za komentowanie skryptu "f\medical\medical_init.sqf", który powodował dosyć dużo błędów w RPT, a nie wnosił nic,
6. Dodanie i naprawa wyświetlania się drużyn (po najechaniu kursorem na gracza).

**Comment by Przemro** [comment]
@Xawery94 
"Dodanie przełączenia trybu ognia na "SAFE" po respawnie," - nie wiem czy to jakoś niezbędne nam ale ok, skoro jest to może ktoś użyje.

"Dodanie ulepszonej notatki "Orbat",
Dodanie ulepszonej notatki "Loadout","
Coś więcej o tym, co zostało dodane, zabrane czy tylko jakieś .rpt poprawione?

"Dodanie i naprawa wyświetlania się drużyn (po najechaniu kursorem na gracza)." - przecież mamy moda który robi coś takiego, że jak patrzysz na kogoś to się pojawia drużyna itp. Chyba, że to jakaś inna opcja o której nie wiem?

**Comment by Xawery94** [comment]
W "Orbat" został poprawiony podział na drużyny tak aby było widać członków wszystkich drużyn, natomiast "Loadout" został przetłumaczony oraz dodana została nowa szata graficzna.

Jeśli chodzi o wyświetlanie drużyn to owszem używamy takiego skryptu, który robi coś takiego lecz przez nieznane błędy się nie wykonywał, więc został on poprawiony aby wszystko działało jak należy.
