### ISSUE TITLE
Ulepszenie BAF

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#76]
Jednostki z BAF`u nie zostały skończone, trzeba im poprawić wyposażenie do aktualnych standardów.

Zmniejszyć ogólną liczbę amunicji.
Zróżnicować plecaki i dodać ich więcej.
Dostosować wyposażenie w pleckach tak aby nie były przepełnione ani za puste.

**Comment by Xawery94** [comment]
Przenoszę na kolejny update.

**Comment by Przemro** [comment]
Dodane, zostało sprawdzić- błedy w nowych ticketach.
