### ISSUE TITLE
Nowa frakcja

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#77]
Mam pomysł na dodanie nowej frakcji do BLUFOR. Byliby to pseudo rebelianci/PMC oparci o amerykańską broń (m4/m16/m60 itp.)

**Comment by Xawery94** [comment]
Przenoszę na kolejny update.

**Comment by Przemro** [comment]
Dodane zostały jednostki Takistanu, jednostki PMC/rebelianci nadal w produkcji, do niedzieli powinny być gotowe.

**Comment by Przemro** [comment]
Na chwilę obecną nie ma za bardzo żadnej frakcji która można by dodać, w skrajności PMC ale bylbi tacy sobie więc zamykam.
