### ISSUE TITLE
Ilość amunicji

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#78]
Czasami przy wyposażeniu "normal" postać dostaje 2 magazynki (jeden w broni załadowany drugi w kamizelce) o wadze 5 magazynków. Trzeba sprawdzić co powoduje taki błąd i naprawić go.

**Comment by Xawery94** [comment]
Na aktualnym szablonie nie udało mi się wywołać tego błędu. Możliwe że coś nie działało ze względu na ten plecak MMG który został ostatnio poprawiony. Teraz wszystko działa poprawnie.

**Comment by Przemro** [comment]
Tyko to sie zdarzało na medyku/dowódcy itp. trzeba na dedyku zrobić test.

**Comment by Xawery94** [comment]
Przenoszę na kolejny update. Wymaga więcej testów.

**Comment by Przemro** [comment]
Dziś było "średnie" i nie było problemu. Wygląda, że to był wcześniej gdzieś mały błąd albo arma się bawiła. Zamykam.
