### ISSUE TITLE
Radia długie

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#80]
Na sobotniej misji (31.10.15) wszystkie radia długie miały różne częstotliwości na tym samym kanale. Trzeba sprawdzić czy to jednorazowy bug czy jakiś błąd.

**Comment by Xawery94** [comment]
Sprawdziłem to i z moich testów nic nie wynikło. Jak sprawdzałem to misja była zrobiona na starszym szablonie prze zmianami w TFR, więc nie mam pojęcia co powodowało ten błąd. Możliwe, że był jakiś desync i coś nie poszło. W każdym razie mi nie udało się odtworzyć tego błędu i nie wiem co go spowodowało.
