### ISSUE TITLE
Dodanie śniegu do opcji misji

### ISSUE THREAD

**Issue by Przemro** [Przemro/Szablon-misji#84]
Ostatnio pojawił się ciekawy skrypt, który dodaje efekt śniegu do A3. Na śnieżne mapy może się przydać, szczególnie że ostatnio pojawiła się zimowa wersja cherno. Skrypt dostępny tutaj: https://forums.bistudio.com/topic/185327-mky-blizzard-and-snow-script/

**Comment by Xawery94** [comment]
Aktualny skrypt działa lokalnie i wygląda to tak:
![Snow](http://zapodaj.net/5890662d9f73c.png.html)

**Comment by Przemro** [comment]
Zamykam, nie zapowiada się by miał nastąpić tutaj jakiś postęp. Jak coś się pojawi to się otworzy lub zrobi nowy ticket.
