### ISSUE TITLE
Ammo MMG,MAT

### ISSUE THREAD

**Issue by Xawery94** [Przemro/Szablon-misji#88]
Dodanie do wyposażenia skrzyń amunicji dla MMG, MAT

**Comment by Przemro** [comment]
Kwestia czy dodać do zwykłych czy zrobić specjalne dla nich. Ale raczej szkoda kombinować z nową skrzynką.

**Comment by Xawery94** [comment]
Aktualnie zostanie dodane do skrzyń odpowiednio:
Skrzynia mała:
- MMG 5,
- MAT 5,

Skrzynia średnia:
- MMG 10,
- MAT 10,

Skrzynia duża:
- MMG 20,
- MAT 20,

**Comment by Xawery94** [comment]
Zostało dodane i zostanie wprowadzone w najbliższym update.

**Comment by Xawery94** [comment]
Zrobione. Ewentualne błędy w kolejnych zgłoszeniach.
